### ISSUE TITLE
how-to-pip-or-easy-install-tkinter-on-windows

### ISSUE THREAD

**Issue by WK-GiHu** [SchuppiM/Python-tkTable#2]
Are you familiar with [how-to-pip-or-easy-install-tkinter-on-windows](https://stackoverflow.com/questions/20044559/how-to-pip-or-easy-install-tkinter-on-windows)

Verify if you have [C:\Tcl\bin\wish85](https://tkdocs.com/tutorial/install.html#installwin)

Verify you have [TCL_LIBRARY and TK_LIBRARY to be set](https://bitbucket.org/anthony_tuininga/cx_freeze/issues/155/required-environment-variables-tcl_library)
Show the ouput of:

    import tkinter
    root = tkinter.Tk()
    print(root.tk.exprstring('$tcl_library'))
    print(root.tk.exprstring('$tk_library'))

**Comment by SchuppiM** [comment]
I installed tkinter with this "pip.exe install tkinter", it is working fine for other widgets.
But I don't have any wish85 Folder on my PC... Do I Need to install something?
TCL_LIBRARY and TK_LIBRARY are there.
The out put you requested is:
C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\tcl\tcl8.6
C:/Users/mschuppisser.EAD/AppData/Local/Programs/Python/Python37-32/tcl/tk8.6

**Comment by WK-GiHu** [comment]
@SchuppiM 

> But I don't have any wish85 Folder on my PC...

Sorry, my bad. The importand directory are `C:\Tcl\bin`.
Verify if you have `C:\Tcl\bin`?
`wish85` is a executable, on Windows it's probably `wish85.exe`.

>  Do I Need to install something?
> I installed tkinter with this "pip.exe install tkinter", it is working fine for other widgets.

As `tkinter` works in general you should have the needed `tcl` librarys.
We need to  know, **where** are these `tcl` librarys installed, and the `\Tktable2.11` folder have to go also there.

> TCL_LIBRARY and TK_LIBRARY are there.
> The out put you requested is:
> C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\tcl\tcl8.6

Hmm, **one** Windows notation using `\` and **one** Python/Unix notation using `/`.
For now i think this doesn't matter.

The output looks OK, your `\Tktable2.11` folder is allready there.
Means: `"C:\...\Python37-32\tcl\Tktable2.11"` is OK.

**Comment by SchuppiM** [comment]
@WK-GiHu
I don't have a C:\Tcl\bin, but I have a C:\ActiveTcl\bin. Don't know if this is the same?
Yes, tkinter is working fine, I tried several widgets. Even tkintertable.
I have a tcl lib right in the Python37-32 Folder: C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\tcl
Hope this helps.
