### ISSUE TITLE
_tkinter.TclError: invalid command name "table"

### ISSUE THREAD

**Issue by WK-GiHu** [SchuppiM/Python-tkTable#3]
### Please confirm:

- [x] The `tktable.dll` and `*.tcl` files are in `...Python37-32\tcl\Tktable2.11`?
- [x] The ouput of  `print(tkable_lib)` before line 126, is `...Python37-32\tcl\Tktable2.11`?
- [x] Content of `...\Python37-32\tcl\Tktable2.11\pkgIndex.tcl`  
  Should be in sync with: `master.tk.call('package', 'require', 'Tktable')` - OK
- [ ] The output of `print(_TKTABLE_LOADED), after line 133`, is `True`? - **NO**
- [x] Verify if the file `...\Python37-32\tcl\Tktable2.11\pkgIndex.tcl` are used at all?
- [ ] [The default search path for tcl packages from the Python Tcl/Tk is `Python23\tcl\*`](https://grokbase.com/t/python/python-list/0448s6h65s/tcl-tk-extension-access-from-python-under-windows)

**Comment by WK-GiHu** [comment]
@SchuppiM 

> The output of print(_TKTABLE_LOADED), after line 133, is True: No

Show the content of `...\Python37-32\tcl\Tktable2.11\pkgIndex.tcl`.

**Comment by SchuppiM** [comment]
@WK-GiHu
Here you go:
if {[catch {package require Tcl 8.2}]} return
package ifneeded Tktable 2.11 "package require Tk 8.2; [list load [file join $dir Tktable.dll] Tktable]"
I have tcl8.6 and tk8.6 installed... could this be the problem?

**Comment by WK-GiHu** [comment]
@SchuppiM 

> I have tcl8.6 and tk8.6 installed... could this be the problem?

Yes, but if the `*.dll` build for `Tcl 8.2` i can't imagin, it will work with `Tcl 8.6`.

---

Three options:

1.  Try it and change both strings to `8.6`

1. Install `Tcl/Tk 8.2`

1.  Deinstall, `Tcl/Tk 8.6` and install `Tcl/Tk 8.2`

**Comment by SchuppiM** [comment]
Changing to 8.6 didn't change anything.
Since other tkinter scripts work with 8.6, do I really have to deinstall 8.6?
Or can I add 8.2?
Any idea where I can get 8.2 from?

**Comment by SchuppiM** [comment]
@WK-GiHu
Changing to 8.6 didn't change anything.
Since other tkinter scripts work with 8.6, do I really have to deinstall 8.6?
Or can I add 8.2?
Any idea where I can get 8.2 from?

**Comment by WK-GiHu** [comment]
@SchuppiM 

> Changing to 8.6 didn't change anything.

Compared to my `pkgIndex.tcl` there is also the string `8.2`, but my `tcl` version is `8.6`.
### My `pkgIndex.tcl`:

    if {[catch {package require Tcl 8.2}]} return
    package ifneeded Tktable 2.10 \
        [list load [file join $dir Tktable.dll] Tktable]


> Or can I add 8.2?
> Any idea where I can get 8.2 from?

You are right, updated to **three** options
Hmm, look into `C:\ActiveTcl`
[wiki.tcl-lang.org](https://wiki.tcl-lang.org/)
[www.tcl.tk/software/tcltk/8.2.html](https://www.tcl.tk/software/tcltk/8.2.html)

---

Verify if the file `...\Python37-32\tcl\Tktable2.11\pkgIndex.tcl` are used at all
Rename ` [file join $dir Tktable.dll]` in ` [file join $dir XTktable.dll]` or remove the whole file.

**Comment by SchuppiM** [comment]
@WK-GiHu
I renamed all the three files in Python37-32\tcl\Tktable2.11: same error.
Then I renamed the three files C:\ActiveTcl\lib (where I got them to copied them in to the Python folder) in as well: Same error.
TKTABLE_LIBRARY is still pointing at: C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\tcl\Tktable2.11
So, I think it is not coming this fare to use the files…… odd.

**Comment by WK-GiHu** [comment]
@SchuppiM 

> I renamed all the three files 

Bad test, as **not** existing leads to the same `TclError`.
The **real** Error is hidden behind the `try: ... except:` block.

Change in `...\Python37-32\Lib\lib-tk\tktable.py` **Line 132** to:

            except tkinter._tkinter.TclError as e:
                print('TclError:{}'.format(e))
                _TKTABLE_LOADED = False

### Try now, without the steps below!
Maybe this *real* `TclError` is more usefull.

---

To force a **bad** *.dll name, do by changing to `XTktable.dll`

    [file join $dir Tktable.dll] in [file join $dir XTktable.dll]

This should output:

    TclError:cannot find symbol "Xtktable_Init": <path to pkgIndex.tcl>: undefined symbol: _Xtktable_Init

Now, we can be shure, this `pkgIndex.tcl` is used.

**Comment by SchuppiM** [comment]
@WK-GiHu
Ok, it did complain about the print('TclError:{}'.format(e)): NameError: name 'e' is not defined
But, how ever, it also printed:
master.tk.call('package', 'require', 'Tktable')
_tkinter.TclError: couldn't load library "C:/Users/mschuppisser.EAD/AppData/Local/Programs/Python/Python37-32/tcl/Tktable2.11/Tktable.dll": Bad exe format. Possibly a 32/64-bit mismatch.
I'm running Win 8.1 64 bit.
How can I user tkTable under 64 bid? All other tkinter components seem to work with 64 bit, even thintertable.

**Comment by SchuppiM** [comment]
Oh, This is the ActiveTCL I installed: ActiveTcl-8.6.8.0-MSWin32-x64
This is where I got the TCL/TK.
I can't find a tktable for Windows 64 bit... only for Linux.

**Comment by WK-GiHu** [comment]
@SchuppiM 

> But, how ever, it also printed:

    master.tk.call('package', 'require', 'Tktable')
    _tkinter.TclError: couldn't load library "C:/.../Python/Python37-32/tcl/Tktable2.11/Tktable.dll": 
    Bad exe format. Possibly a 32/64-bit mismatch.

### Oh, what a bad idea to hide the real `TclError`, a simple Version mismatch!

> This is the ActiveTCL I installed: ActiveTcl-8.6.8.0-MSWin32-x64

Have you ever tried to run this ActiveTcl?
I don't see a `8.6.8.0-MSWin32-x64` only `8.6.8.0 Windows (64-bit, x64)`

**Comment by SchuppiM** [comment]
@WK-GiHu
Yes, I had to download tktable extra. It didn't come with Pythons tkinter.

**Comment by SchuppiM** [comment]
The Link you sent Points at 8.6.8.0. This is the Version I have already installed: ActiveTcl-8.6.8.0-MSWin32-x64. So, no need for a second install I think.

How can I run this under 64 bit Windows? Any idea?

**Comment by SchuppiM** [comment]
I can't see your new text in here, only in my mailbox!

Yes, tktable.dll is included, but not tktable.py. I had to download tktable.py.

Inspect is telling me that the tktable.dll is a 64bit dll.
But Python and the tcl and tk is is using are 32 bit..... :-(

This means I need to get a 32 bit tktable.dll........ searching for it....
