### ISSUE TITLE
_tkinter.TclError: couldn't load library

### ISSUE THREAD

**Issue by WK-GiHu** [SchuppiM/Python-tkTable#5]
@SchuppiM 
> But, how ever, it also printed:

    master.tk.call('package', 'require', 'Tktable')
    _tkinter.TclError: couldn't load library "C:/.../Python/Python37-32/tcl/Tktable2.11/Tktable.dll": 
    Bad exe format. Possibly a 32/64-bit mismatch.

### Oh, what a bad idea to hide the real `TclError`, a simple Version mismatch!

Relevant: 
 - [My DLL was 32-bit and my Python distribution was 64-bit and 64-bit python can't load a 32-bit DLL..](https://stackoverflow.com/questions/20945596/python-tksnack-is-giving-me-errors)  
 - [can-i-use-32bit-dll-or-exe-in-64bit-python](https://stackoverflow.com/questions/11642134/can-i-use-32bit-dll-or-exe-in-64bit-python)
 - [cross-compiling](https://wiki.tcl-lang.org/page/cross-compiling)

---

> I can't find a tktable for Windows 64 bit... only for Linux.

Did you need to install `tktable` extra?

Here [Download Tcl – ActiveTcl Community Edition](https://www.activestate.com/products/activetcl/downloads/) i see both `Windows (64-bit, x64)` and `Windows (x86)`, states `TkTable` is included:

    We’ve pre-bundled a number of Tcl modules in our ActiveTcl 8.6.8 release:
    Crticl, TclSOAP, Snack, TkCon, BWidget, [incr Tk], Tcllib, TclX, Expect, Tls, Tklib, TkTable, Tclvfs,  Metakit, Tbcload, Img, Treectrl, Wub, Nsf, Trofs, [incr widgets]

**Comment by WK-GiHu** [comment]
@SchuppiM 

> Yes, I had to download tktable extra. It didn't come with Pythons tkinter.

Show me the link, where you get this extra download `tktable`
As commented above, ActiveTcl states `TkTable` **is included**!


> The Link you sent Points at 8.6.8.0. This is the Version I have already installed: ActiveTcl-8.6.8.0-MSWin32-x64. So, no need for a second install I think.

Did you say, the version named `Windows (64-bit, x64)` online, results in `ActiveTcl-8.6.8.0-MSWin32-x64`?

Verify the `tktable.dll` with a tool like [ inpspectExd](https://stackoverflow.com/a/27153607/7414759) to know it's `64-bit, x64` or `32-bit, x64` or whatever. You have to get this info from your used `Python` and used `tcl` as well, see the links in my privious comment.

> How can I run this under 64 bit Windows? Any idea?

Confirm: 
 - [x] Run a `32-bit` Windows on a `64-bit` CPU.
 - [ ] Run a `64-bit` Windows on a `64-bit` CPU.

**Comment by WK-GiHu** [comment]
@SchuppiM 

> I can't see your new text in here, only in my mailbox!

I have **closed** the issue `invalid command name "table"` and opend a new issue `couldn't load library`. Go to **all** Issues.

---

> Yes, tktable.dll is included, but not tktable.py. I had to download tktable.py.

`tktable.py` is Python source, this is not related to any OS or CPU.
Your installed/used Python version loads `tktable.py` => `tkinter` =>  `tcl` => `pkgIndex.tcl` => `tkTable.dll`.

 - [x] Inspect is telling me that the tktable.dll is a 64bit dll.
 - [x] But Python and the tcl and tk is is using are 32 bit..... :-(

>This means I need to get a 32 bit tktable.dll........ searching for it....

Yes, see my link above in the first comment.

**Comment by SchuppiM** [comment]
@WK-GiHu:
Download Tcl – ActiveTcl Community Edition: This is where I got ti from. But, when installing, it doesn't give me the Option to install it as 32 bit Version.

**Comment by SchuppiM** [comment]
@WK-GiHu:
I'm thinking if it's better to install Python 64 bit Version..... might be better....

**Comment by SchuppiM** [comment]
@WK-GiHu
After installing Python 64 bit Version, I got the small script running.
Now having Problems with Setting it up again...
Thx so much for your help!
