### ISSUE TITLE
NameError: name 'e' is not defined

### ISSUE THREAD

**Issue by WK-GiHu** [SchuppiM/Python-tkTable#6]
@SchuppiM 

> Ok, it did complain about the print('TclError:{}'.format(e)): NameError: name 'e' is not defined

Show the full `try: ... except:` block

**Comment by SchuppiM** [comment]
@WK-GiHu: Here you go:
            try:
                master.tk.call('package', 'require', 'Tktable')
                _TKTABLE_LOADED = True
            except tkinter._tkinter.TclError:
                print('TclError:{}'.format(e))
                _TKTABLE_LOADED = False

**Comment by WK-GiHu** [comment]
@SchuppiM 

Should read

    except tkinter._tkinter.TclError as e:

**Comment by SchuppiM** [comment]
@WK-GiHu : Sorry! Didn't see the 'as e'
