### ISSUE TITLE
TkTable.DLL Windows (x86)

### ISSUE THREAD

**Issue by WK-GiHu** [SchuppiM/Python-tkTable#7]
@SchuppiM 
Switch to Issue: `TkTable.DLL Windows (x86)`

> What I found on the net is that the current version of ActiveTcl-8.6.9.8609.2-MSWin32-x64 is not working for 32bit.

You have to go with the `Windows (x86)` Edition.
See, the below table, `8.5.18.0` column `Windows (x86)`.

---
![grafik](https://user-images.githubusercontent.com/22146250/55507957-26877380-5659-11e9-8186-333a567d6603.png)

Here [Download Tcl – ActiveTcl Community Edition](https://www.activestate.com/products/activetcl/downloads/) i see both `Windows (64-bit, x64)` and `Windows (x86)`, states `TkTable` is included:

    We’ve pre-bundled a number of Tcl modules in our ActiveTcl 8.6.8 release:
    Crticl, TclSOAP, Snack, TkCon, BWidget, [incr Tk], Tcllib, TclX, Expect, Tls, Tklib, TkTable, Tclvfs,  Metakit, Tbcload, Img, Treectrl, Wub, Nsf, Trofs, [incr widgets]

**Comment by SchuppiM** [comment]
@WK-GiHu 
Super! It's working! Thx so much!!!!!
